import { parseAbi } from 'viem';

export const baseAgentPaymentGuardAbi = parseAbi([
  'error InvalidToken()',
  'error UnsupportedChain(uint256 chainId)',
  'error InvalidAgent()',
  'error InvalidLimits()',
  'error InvalidExpiry()',
  'error InvalidMerchant()',
  'error SelfPaymentNotAllowed()',
  'error InvalidOwner()',
  'error InvalidAmount()',
  'error InvalidReference()',
  'error PolicyNotConfigured()',
  'error PolicyPaused()',
  'error PolicyIsRevoked()',
  'error PolicyExpired()',
  'error UnauthorizedAgent()',
  'error MerchantNotAllowed()',
  'error PerPaymentLimitExceeded()',
  'error DailyLimitExceeded()',
  'error ReferenceAlreadyUsed()',
  'error TokenTransferFailed()',
  'error Reentrancy()',
  'function stablecoin() view returns (address)',
  'function configurePolicy(address agent, uint256 perPaymentLimit, uint256 dailyLimit, uint64 expiresAt)',
  'function setMerchant(address merchant, bool allowed)',
  'function setPolicyPaused(bool paused)',
  'function revokePolicy()',
  'function executePayment(address owner, address merchant, uint256 amount, bytes32 externalReference) returns (bytes32 receiptId)',
  'function getPolicy(address owner) view returns ((address agent, uint256 perPaymentLimit, uint256 dailyLimit, uint64 expiresAt, bool paused, bool revoked, uint64 revision))',
  'function isMerchantAllowed(address owner, address merchant) view returns (bool)',
  'function isReferenceUsed(address owner, bytes32 externalReference) view returns (bool)',
  'function getDailySpend(address owner) view returns (uint64 day, uint256 spent)',
  'function remainingDailyAllowance(address owner) view returns (uint256)',
  'function computeReceiptId(address owner, address merchant, uint256 amount, bytes32 externalReference) view returns (bytes32)',
  'event PolicyConfigured(address indexed owner, address indexed agent, uint256 perPaymentLimit, uint256 dailyLimit, uint64 expiresAt, uint64 revision)',
  'event MerchantPermissionUpdated(address indexed owner, address indexed merchant, bool allowed)',
  'event PolicyPauseUpdated(address indexed owner, bool paused)',
  'event PolicyRevoked(address indexed owner, uint64 revision)',
  'event PaymentExecuted(bytes32 indexed receiptId, address indexed owner, address indexed agent, address merchant, uint256 amount, bytes32 externalReference, uint64 day, uint256 spentToday, uint64 policyRevision)',
]);

export const erc20ApproveAbi = parseAbi([
  'function approve(address spender, uint256 amount) returns (bool)',
  'function allowance(address owner, address spender) view returns (uint256)',
]);
